# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Build on ${{ matrix.os }}
      run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      name: Upload macOS binary
      if: matrix.os == "macos-latest"
      with:
        name: macOS
        path: out/make/zip/darwin/x64/*.zip
    - uses: actions/upload-artifact@v2 
      name: Upload Windows binary
      if: matrix.os == "windows-latest"
      with:
        name: Windows
        path: out/make/squirrel.windows/x64/*.exe
